### ISSUE TITLE
thaumonomicon bug

### ISSUE THREAD

**Issue by KoTeuKa404** [KELETU66666/RenaissanceCore#2]
![image](https://github.com/user-attachments/assets/c4c7e776-fe99-400d-ba11-0f5da3d3e9ed)
![image](https://github.com/user-attachments/assets/f2cb6795-8e2d-42d1-9755-a085dbaae432)
![image](https://github.com/user-attachments/assets/44c6de68-d3c7-42dc-9d69-93240d92342a)

**Comment by KELETU66666** [comment]
this is a thaumcraft bug i can't fix :(
sorry...
